#!/usr/bin/env python3
"""Locate value-dependent DiT drift at exported block boundaries.

This diagnostic consumes a graph produced by ``make_dit_probe_fixture.py`` with
``--probe-set blocks`` and compares three executions on the same recorded flow
invocations:

1. untouched official TripoSplat PyTorch;
2. the in-memory browser/export adapter in PyTorch;
3. the probed graph in ONNX Runtime CPU.

Only a ``[1, 4, 16]`` slice is retained at each boundary.  The full tensors are
never copied to the report, keeping the probe useful on machines that can load
the production-sized DiT but cannot retain every 12,294-token activation.
"""

from __future__ import annotations

import argparse
import gc
import hashlib
import json
import platform
import time
from pathlib import Path
from typing import Any, Mapping

from dit_common import (
    OFFICIAL_REPOSITORY_URL,
    OUTPUT_NAMES,
    adapt_official_flow_for_onnx,
    choose_torch_device,
    comparison_metrics,
    load_official_flow_model,
    make_browser_flow_step,
    metadata_dict,
    output_mapping,
    sha256_file,
    source_revision,
    synchronize_torch,
    torch_inputs_from_numpy,
)
from validate_dit_onnx import load_trajectory_invocation_fixture


PROBE_PREFIX = "probe_"
PROBE_SHAPE = (1, 4, 16)
PROBE_ORDER = (
    "probe_input_linear",
    "probe_input_positioned",
    "probe_condition_dino",
    "probe_condition_vae",
    "probe_condition_combined",
    "probe_noise_refiner_00_attention_residual",
    "probe_noise_refiner_00",
    "probe_noise_refiner_01_attention_residual",
    "probe_noise_refiner_01",
    "probe_context_refiner_00_attention_residual",
    "probe_context_refiner_00",
    "probe_context_refiner_01_attention_residual",
    "probe_context_refiner_01",
    "probe_combined_tokens",
    "probe_block_00_attention_residual",
    *(f"probe_block_{index:02d}" for index in range(24)),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--triposplat-repo",
        type=Path,
        required=True,
        help=f"Clean local clone of {OFFICIAL_REPOSITORY_URL}.",
    )
    parser.add_argument("--weights", type=Path, required=True)
    parser.add_argument(
        "--probe-onnx",
        type=Path,
        required=True,
        help="Graph generated by make_dit_probe_fixture.py --probe-set blocks.",
    )
    parser.add_argument("--trajectory-fixture-dir", type=Path, required=True)
    parser.add_argument(
        "--invocation",
        action="append",
        type=int,
        dest="invocations",
        help="Recorded one-based invocation. Repeat for a pair (default: 7 and 8).",
    )
    parser.add_argument(
        "--device",
        choices=("cpu", "mps", "cuda", "auto"),
        default="mps",
        help="PyTorch device (default: %(default)s). ORT always uses CPU.",
    )
    parser.add_argument("--session-threads", type=int, default=8)
    parser.add_argument("--atol", type=float, default=1e-5)
    parser.add_argument("--rtol", type=float, default=1e-5)
    parser.add_argument(
        "--material-ratio",
        type=float,
        default=4.0,
        help="Minimum unconditional/conditional max-error ratio (default: %(default)s).",
    )
    parser.add_argument(
        "--material-absolute",
        type=float,
        default=1e-5,
        help="Minimum unconditional max error for material separation (default: %(default)s).",
    )
    parser.add_argument(
        "--low-memory-construction",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    parser.add_argument("--allow-dirty-official-source", action="store_true")
    parser.add_argument("--allow-source-commit-mismatch", action="store_true")
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    args.invocations = args.invocations or [7, 8]
    if len(args.invocations) != 2 or len(set(args.invocations)) != 2:
        parser.error("exactly two distinct --invocation values are required")
    if any(value <= 0 for value in args.invocations):
        parser.error("--invocation values must be positive")
    if args.session_threads <= 0:
        parser.error("--session-threads must be positive")
    if args.atol < 0 or args.rtol < 0:
        parser.error("--atol and --rtol must be non-negative")
    if args.material_ratio <= 1:
        parser.error("--material-ratio must be greater than one")
    if args.material_absolute < 0:
        parser.error("--material-absolute must be non-negative")
    return args


def int_metadata(metadata: Mapping[str, str], name: str) -> int:
    try:
        value = int(metadata.get(name, "0"))
    except ValueError as exc:
        raise ValueError(f"Graph metadata {name!r} is not an integer") from exc
    if value <= 0:
        raise ValueError(f"Graph metadata {name!r} must be positive, got {value}")
    return value


def bool_metadata(metadata: Mapping[str, str], name: str) -> bool:
    raw_value = metadata.get(name, "false")
    if raw_value not in {"true", "false"}:
        raise ValueError(f"Graph metadata {name!r} must be true or false")
    return raw_value == "true"


def adapter_configuration(metadata: Mapping[str, str]) -> dict[str, Any]:
    precision = metadata.get("triposplat.internal_precision")
    if precision not in {"fp16", "fp32"}:
        raise ValueError(
            "Probe graph lacks triposplat.internal_precision fp16/fp32 metadata"
        )
    try:
        head_padding = int(metadata.get("triposplat.attention_head_padding", "-1"))
    except ValueError as exc:
        raise ValueError("Graph attention-head padding metadata is not an integer") from exc
    if head_padding < 0:
        raise ValueError("Graph attention-head padding metadata must be non-negative")
    rms_value = metadata.get("triposplat.rms_norm_eps", "disabled")
    if rms_value == "disabled":
        rms_norm_eps = None
    else:
        rms_norm_eps = float(rms_value)
        if rms_norm_eps <= 0:
            raise ValueError("Graph RMS epsilon must be positive or disabled")
    return {
        "precision": precision,
        "attention_query_chunk": int_metadata(
            metadata, "triposplat.attention_query_chunk"
        ),
        "collapsed_unconditional_context": bool_metadata(
            metadata, "triposplat.collapsed_unconditional_context"
        ),
        "attention_head_chunk": int_metadata(
            metadata, "triposplat.attention_head_chunk"
        ),
        "attention_head_padding": head_padding,
        "qk_norm_padding_tokens": int_metadata(
            metadata, "triposplat.qk_norm_padding_tokens"
        ),
        "rms_norm_eps": rms_norm_eps,
        "attention_output_chunk": int_metadata(
            metadata, "triposplat.attention_output_chunk"
        ),
        "attention_output_reduction_chunk": int_metadata(
            metadata, "triposplat.attention_output_reduction_chunk"
        ),
    }


def to_probe_numpy(value: Any) -> Any:
    import numpy as np

    if not hasattr(value, "shape") or len(value.shape) != 3:
        raise ValueError(f"Expected rank-three probe tensor, got {type(value)}")
    if value.shape[0] != 1 or value.shape[1] < 4 or value.shape[2] < 16:
        raise ValueError(f"Cannot take {PROBE_SHAPE} slice from {tuple(value.shape)}")
    return np.ascontiguousarray(
        value.detach()[:, :4, :16].float().cpu().numpy(), dtype=np.float32
    )


class TorchBoundaryCapture:
    """Attach stable semantic boundary names without modifying official source."""

    def __init__(self, model: Any) -> None:
        self.values: dict[str, Any] = {}
        self.handles: list[Any] = []

        def output_hook(name: str) -> Any:
            def capture(_module: Any, _inputs: Any, output: Any) -> None:
                self.values[name] = to_probe_numpy(output)

            return capture

        def input_hook(name: str) -> Any:
            def capture(_module: Any, inputs: Any) -> None:
                if not inputs:
                    raise ValueError(f"Boundary {name} received no positional input")
                self.values[name] = to_probe_numpy(inputs[0])

            return capture

        self.handles.extend(
            (
                model.input_layer.register_forward_hook(output_hook("probe_input_linear")),
                model.noise_refiner[0].register_forward_pre_hook(
                    input_hook("probe_input_positioned")
                ),
                model.cond_embedder.register_forward_hook(
                    output_hook("probe_condition_dino")
                ),
                model.cond_embedder2.register_forward_hook(
                    output_hook("probe_condition_vae")
                ),
                model.context_refiner[0].register_forward_pre_hook(
                    input_hook("probe_condition_combined")
                ),
                model.blocks[0].register_forward_pre_hook(
                    input_hook("probe_combined_tokens")
                ),
            )
        )
        for index, block in enumerate(model.noise_refiner):
            self.handles.append(
                block.norm2.register_forward_pre_hook(
                    input_hook(f"probe_noise_refiner_{index:02d}_attention_residual")
                )
            )
            self.handles.append(
                block.register_forward_hook(output_hook(f"probe_noise_refiner_{index:02d}"))
            )
        for index, block in enumerate(model.context_refiner):
            self.handles.append(
                block.norm2.register_forward_pre_hook(
                    input_hook(f"probe_context_refiner_{index:02d}_attention_residual")
                )
            )
            self.handles.append(
                block.register_forward_hook(output_hook(f"probe_context_refiner_{index:02d}"))
            )
        self.handles.append(
            model.blocks[0].norm2.register_forward_pre_hook(
                input_hook("probe_block_00_attention_residual")
            )
        )
        for index, block in enumerate(model.blocks):
            self.handles.append(
                block.register_forward_hook(output_hook(f"probe_block_{index:02d}"))
            )

    def begin(self) -> None:
        self.values = {}

    def finish(self) -> dict[str, Any]:
        missing = [name for name in PROBE_ORDER if name not in self.values]
        extra = [name for name in self.values if name not in PROBE_ORDER]
        if missing or extra:
            raise RuntimeError(f"PyTorch probe mismatch: missing={missing}, extra={extra}")
        return {name: self.values[name] for name in PROBE_ORDER}

    def close(self) -> None:
        for handle in self.handles:
            handle.remove()
        self.handles = []


def torch_outputs_to_numpy(outputs: Any) -> dict[str, Any]:
    import numpy as np

    return {
        name: np.ascontiguousarray(value.detach().float().cpu().numpy(), dtype=np.float32)
        for name, value in output_mapping(outputs).items()
    }


def run_torch_invocation(
    torch: Any,
    graph: Any,
    capture: TorchBoundaryCapture,
    inputs: Mapping[str, Any],
    device: Any,
) -> tuple[dict[str, Any], dict[str, Any], float]:
    tensors = torch_inputs_from_numpy(torch, inputs, device)
    capture.begin()
    synchronize_torch(torch, device)
    started = time.perf_counter()
    with torch.inference_mode():
        outputs = graph(*tensors)
    synchronize_torch(torch, device)
    duration_ms = (time.perf_counter() - started) * 1000.0
    result = torch_outputs_to_numpy(outputs)
    probes = capture.finish()
    del tensors, outputs
    return result, probes, duration_ms


def compare_maps(
    reference: Mapping[str, Any],
    candidate: Mapping[str, Any],
    names: tuple[str, ...],
    atol: float,
    rtol: float,
) -> dict[str, Any]:
    return {
        name: comparison_metrics(reference[name], candidate[name], atol, rtol)
        for name in names
    }


def pass_name(source: str) -> str:
    marker = " pass="
    if marker not in source:
        return "unknown"
    return source.rsplit(marker, 1)[1]


def array_sha256(value: Any) -> str:
    import numpy as np

    array = np.ascontiguousarray(value)
    return hashlib.sha256(memoryview(array).cast("B")).hexdigest()


def separation_summary(
    invocations: Mapping[int, Mapping[str, Any]],
    ratio: float,
    absolute: float,
) -> dict[str, Any]:
    conditional = next(
        (value for value in invocations.values() if value["pass"] == "conditional"),
        None,
    )
    unconditional = next(
        (value for value in invocations.values() if value["pass"] == "unconditional"),
        None,
    )
    if conditional is None or unconditional is None:
        return {
            "available": False,
            "reason": "The selected pair must contain one conditional and one unconditional call.",
        }

    first_unconditional_only_failure = None
    first_material_ratio = None
    progression = []
    for name in PROBE_ORDER:
        cond = conditional["comparisons"]["ort_vs_official"][name]
        uncond = unconditional["comparisons"]["ort_vs_official"][name]
        cond_max = float(cond["max_absolute_error"])
        uncond_max = float(uncond["max_absolute_error"])
        observed_ratio = uncond_max / max(cond_max, 1e-30)
        item = {
            "boundary": name,
            "conditional_max_absolute_error": cond_max,
            "unconditional_max_absolute_error": uncond_max,
            "unconditional_to_conditional_ratio": observed_ratio,
            "conditional_passed": bool(cond["passed"]),
            "unconditional_passed": bool(uncond["passed"]),
        }
        progression.append(item)
        if (
            first_unconditional_only_failure is None
            and cond["passed"]
            and not uncond["passed"]
        ):
            first_unconditional_only_failure = item
        if (
            first_material_ratio is None
            and uncond_max >= absolute
            and observed_ratio >= ratio
        ):
            first_material_ratio = item
    return {
        "available": True,
        "thresholds": {
            "material_absolute": absolute,
            "material_ratio": ratio,
        },
        "first_unconditional_only_tolerance_failure": first_unconditional_only_failure,
        "first_material_ratio_separation": first_material_ratio,
        "progression": progression,
    }


def validate(args: argparse.Namespace) -> dict[str, Any]:
    try:
        import numpy as np
        import onnx
        import onnxruntime as ort
        import torch
    except ImportError as exc:
        raise SystemExit(f"PyTorch, ONNX, ONNX Runtime, and NumPy are required: {exc}") from exc

    graph_path = args.probe_onnx.expanduser().resolve()
    if not graph_path.is_file():
        raise FileNotFoundError(graph_path)
    graph_proto = onnx.load_model(str(graph_path), load_external_data=False)
    metadata = metadata_dict(graph_proto)
    recorded_probe_count = int(metadata.get("triposplat.diagnostic_probes", "0"))
    output_names = tuple(value.name for value in graph_proto.graph.output)
    probe_names = tuple(name for name in output_names if name.startswith(PROBE_PREFIX))
    if probe_names != PROBE_ORDER or recorded_probe_count != len(PROBE_ORDER):
        raise ValueError(
            "Probe graph does not expose the expected ordered block boundary set: "
            f"metadata_count={recorded_probe_count}, outputs={probe_names}"
        )
    for value in graph_proto.graph.output:
        if value.name not in PROBE_ORDER:
            continue
        shape = tuple(dimension.dim_value for dimension in value.type.tensor_type.shape.dim)
        if shape != PROBE_SHAPE:
            raise ValueError(f"Probe {value.name} has shape {shape}; expected {PROBE_SHAPE}")

    config = adapter_configuration(metadata)
    if config["collapsed_unconditional_context"]:
        raise ValueError(
            "Collapsed unconditional-context probe graphs are unsupported: this "
            "validator requires a paired conditional call, which is invalid for an "
            "unconditional-only graph. Use validate_dit_onnx.py with an all-zero "
            "unconditional invocation instead."
        )
    repo = args.triposplat_repo.expanduser().resolve()
    commit, dirty = source_revision(repo)
    if dirty and not args.allow_dirty_official_source:
        raise RuntimeError("Official model.py/triposplat.py have tracked edits")
    exported_commit = metadata.get("triposplat.source_commit", "unknown")
    if (
        commit != "unknown"
        and exported_commit != "unknown"
        and commit != exported_commit
        and not args.allow_source_commit_mismatch
    ):
        raise RuntimeError(
            f"Official commit {commit} differs from probe graph commit {exported_commit}"
        )

    records: dict[int, dict[str, Any]] = {}
    loaded_inputs: dict[int, Mapping[str, Any]] = {}
    expected_outputs: dict[int, Mapping[str, Any]] = {}
    for invocation in args.invocations:
        inputs, expected, source = load_trajectory_invocation_fixture(
            args.trajectory_fixture_dir, invocation
        )
        loaded_inputs[invocation] = inputs
        expected_outputs[invocation] = expected
        records[invocation] = {
            "source": source,
            "pass": pass_name(source),
            "conditioning": {
                name: {
                    "sha256": array_sha256(inputs[name]),
                    "nonzero_values": int(np.count_nonzero(inputs[name])),
                    "max_absolute_value": float(np.abs(inputs[name]).max()),
                }
                for name in ("feature1", "feature2")
            },
        }

    first_inputs = loaded_inputs[args.invocations[0]]
    second_inputs = loaded_inputs[args.invocations[1]]
    paired_dynamic_inputs = {
        name: {
            "exactly_equal": bool(np.array_equal(first_inputs[name], second_inputs[name])),
            "sha256": array_sha256(first_inputs[name]),
        }
        for name in ("latent", "camera", "t")
    }
    if not all(item["exactly_equal"] for item in paired_dynamic_inputs.values()):
        raise ValueError(
            "Selected conditional/unconditional calls do not share latent, camera, and t"
        )

    device = choose_torch_device(torch, args.device)
    print(f"Loading official {config['precision']} flow model on {device}", flush=True)
    model, source = load_official_flow_model(
        torch=torch,
        triposplat_repo=repo,
        weights=args.weights,
        device=device,
        internal_precision=config["precision"],
        low_memory_construction=args.low_memory_construction,
    )
    capture = TorchBoundaryCapture(model)
    official_graph = make_browser_flow_step(torch, model, config["precision"])
    official_values: dict[int, dict[str, Any]] = {}
    official_probes: dict[int, dict[str, Any]] = {}
    for invocation in args.invocations:
        print(f"Official PyTorch invocation {invocation}", flush=True)
        values, probes, duration = run_torch_invocation(
            torch, official_graph, capture, loaded_inputs[invocation], device
        )
        official_values[invocation] = values
        official_probes[invocation] = probes
        records[invocation]["timings_ms"] = {"official_pytorch": duration}

    adapter_metadata = adapt_official_flow_for_onnx(
        torch,
        model,
        source.model_module,
        attention_query_chunk=config["attention_query_chunk"],
        collapsed_unconditional_context=config[
            "collapsed_unconditional_context"
        ],
        attention_head_chunk=config["attention_head_chunk"],
        attention_head_padding=config["attention_head_padding"],
        qk_norm_padding_tokens=config["qk_norm_padding_tokens"],
        rms_norm_eps=config["rms_norm_eps"],
        attention_output_chunk=config["attention_output_chunk"],
        attention_output_reduction_chunk=config["attention_output_reduction_chunk"],
    )
    adapted_graph = make_browser_flow_step(torch, model, config["precision"])
    adapted_values: dict[int, dict[str, Any]] = {}
    adapted_probes: dict[int, dict[str, Any]] = {}
    for invocation in args.invocations:
        print(f"Adapted PyTorch invocation {invocation}", flush=True)
        values, probes, duration = run_torch_invocation(
            torch, adapted_graph, capture, loaded_inputs[invocation], device
        )
        adapted_values[invocation] = values
        adapted_probes[invocation] = probes
        records[invocation]["timings_ms"]["adapted_pytorch"] = duration

    capture.close()
    del capture, official_graph, adapted_graph, model, source
    gc.collect()
    if device.type == "cuda":
        torch.cuda.empty_cache()
    elif device.type == "mps":
        torch.mps.empty_cache()

    options = ort.SessionOptions()
    options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
    options.log_severity_level = 3
    options.intra_op_num_threads = args.session_threads
    print("Loading probed graph in ONNX Runtime CPU", flush=True)
    session_started = time.perf_counter()
    session = ort.InferenceSession(
        str(graph_path), sess_options=options, providers=["CPUExecutionProvider"]
    )
    session_load_ms = (time.perf_counter() - session_started) * 1000.0
    session_output_names = tuple(value.name for value in session.get_outputs())
    if session_output_names != output_names:
        raise ValueError(
            f"ORT output order differs from graph: {session_output_names} vs {output_names}"
        )

    for invocation in args.invocations:
        print(f"ONNX Runtime CPU invocation {invocation}", flush=True)
        started = time.perf_counter()
        raw_outputs = session.run(list(output_names), dict(loaded_inputs[invocation]))
        duration = (time.perf_counter() - started) * 1000.0
        candidate = {
            name: np.ascontiguousarray(np.asarray(value, dtype=np.float32))
            for name, value in zip(output_names, raw_outputs)
        }
        ort_values = {name: candidate[name] for name in OUTPUT_NAMES}
        ort_probes = {name: candidate[name] for name in PROBE_ORDER}
        records[invocation]["timings_ms"]["onnxruntime_cpu"] = duration
        records[invocation]["comparisons"] = {
            "official_vs_recorded_fixture": compare_maps(
                expected_outputs[invocation],
                official_values[invocation],
                OUTPUT_NAMES,
                args.atol,
                args.rtol,
            ),
            "adapted_vs_official_final": compare_maps(
                official_values[invocation],
                adapted_values[invocation],
                OUTPUT_NAMES,
                args.atol,
                args.rtol,
            ),
            "ort_vs_official_final": compare_maps(
                official_values[invocation],
                ort_values,
                OUTPUT_NAMES,
                args.atol,
                args.rtol,
            ),
            "adapted_vs_official": compare_maps(
                official_probes[invocation],
                adapted_probes[invocation],
                PROBE_ORDER,
                args.atol,
                args.rtol,
            ),
            "ort_vs_official": compare_maps(
                official_probes[invocation],
                ort_probes,
                PROBE_ORDER,
                args.atol,
                args.rtol,
            ),
            "ort_vs_adapted": compare_maps(
                adapted_probes[invocation],
                ort_probes,
                PROBE_ORDER,
                args.atol,
                args.rtol,
            ),
        }

    separation = separation_summary(
        records,
        ratio=args.material_ratio,
        absolute=args.material_absolute,
    )
    strict_final_passed = all(
        all(
            bool(metrics["passed"])
            for metrics in record["comparisons"]["ort_vs_official_final"].values()
        )
        for record in records.values()
    )
    return {
        "passed": strict_final_passed,
        "component": "flow_dit_conditional_unconditional_block_boundary_probe",
        "scope": (
            "First four latent-side tokens and first sixteen channels at embeddings, "
            "two noise refiners, two context refiners, concatenation, and 24 joint blocks."
        ),
        "source": {
            "repository": OFFICIAL_REPOSITORY_URL,
            "checkout": str(repo),
            "commit": commit,
            "tracked_source_dirty": dirty,
            "weights": str(args.weights.expanduser().resolve()),
            "trajectory_fixture": str(args.trajectory_fixture_dir.expanduser().resolve()),
        },
        "graph": {
            "path": str(graph_path),
            "sha256": sha256_file(graph_path),
            "bytes": graph_path.stat().st_size,
            "external_data": metadata.get("triposplat.external_data"),
            "probe_count": len(PROBE_ORDER),
            "probe_shape": list(PROBE_SHAPE),
            "internal_precision": config["precision"],
            "collapsed_unconditional_context": config[
                "collapsed_unconditional_context"
            ],
        },
        "runtime": {
            "platform": platform.platform(),
            "torch": torch.__version__,
            "torch_device": str(device),
            "onnxruntime": ort.__version__,
            "onnxruntime_provider": "CPUExecutionProvider",
            "onnxruntime_graph_optimization": "ORT_DISABLE_ALL",
            "onnxruntime_session_threads": args.session_threads,
            "onnxruntime_session_load_ms": session_load_ms,
            "timings_are_browser_benchmarks": False,
        },
        "tolerance": {"absolute": args.atol, "relative": args.rtol},
        "paired_dynamic_inputs": paired_dynamic_inputs,
        "adapter": adapter_metadata.__dict__,
        "invocations": {str(key): value for key, value in records.items()},
        "conditional_unconditional_separation": separation,
        "interpretation": {
            "probe_is_full_tensor_gate": False,
            "reason": (
                "The boundary probes intentionally retain only 64 values per activation. "
                "They localize drift but do not replace full-output numerical gates."
            ),
        },
    }


def main() -> None:
    args = parse_args()
    report = validate(args)
    destination = args.report.expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    separation = report["conditional_unconditional_separation"]
    print(f"Wrote {destination}")
    print(
        json.dumps(
            {
                "passed": report["passed"],
                "first_unconditional_only_tolerance_failure": separation.get(
                    "first_unconditional_only_tolerance_failure"
                ),
                "first_material_ratio_separation": separation.get(
                    "first_material_ratio_separation"
                ),
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
